spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prompt_saas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  # JMX Configuration to fix connection issues
  jmx:
    enabled: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**,templates/**
    livereload:
      enabled: true
      port: 35729

server:
  port: 8080
