spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prompt_saas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false # Disabled for security in production
    properties:
      hibernate:
        format_sql: false # Disabled for security in production

  flyway:
    enabled: true
    locations: classpath:db/migration

  # JMX Configuration to fix connection issues
  jmx:
    enabled: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**,templates/**
    livereload:
      enabled: true
      port: 35729

server:
  port: 8080
  # Security headers
  servlet:
    context-path: /
  # Error handling
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

# Logging configuration
logging:
  level:
    com.alejandro.microservices.promptgeneratorsaas: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    com.stripe: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 30

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-change-in-production}
  access:
    expiration: 900 # 15 minutes in seconds
  refresh:
    expiration: 604800 # 7 days in seconds
  issuer: prompt-generator-saas

# CORS Configuration
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}

# AI Provider Configuration
openai:
  api:
    key: ${OPENAI_API_KEY:}
  model: ${OPENAI_MODEL:gpt-4o-mini}

claude:
  api:
    key: ${CLAUDE_API_KEY:}
  model: ${CLAUDE_MODEL:claude-3-opus-20240229}

stable-diffusion:
  api:
    url: ${STABLE_DIFFUSION_API_URL:https://api.stability.ai}
    key: ${STABLE_DIFFUSION_API_KEY:}
  model: ${STABLE_DIFFUSION_MODEL:stable-diffusion-xl-1024-v1-0}

# Stripe Configuration
stripe:
  secret-key: ${STRIPE_SECRET_KEY:sk_test_xxxxxxxxxxxxxxxxxxxxxx}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_xxxxxxxxxxxxxxxxxxxxxx}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:pk_test_xxxxxxxxxxxxxxxxxxxxxx}
